### ISSUE TITLE
cannot find module named dlmodels?

### ISSUE THREAD

**Issue by happog** [NVlabs/ocroseg#1]
>>> seg = ocroseg.Segmenter("lowskew-000000259-011440.pt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ocroseg/segmentation.py", line 300, in __init__
    self.model = torch.load(mname)
  File "/home/sunday/dingyk/tf2/local/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/sunday/dingyk/tf2/local/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/home/sunday/dingyk/tf2/local/lib/python2.7/site-packages/dltrainers/__init__.py", line 4, in <module>
    from trainers import *
  File "/home/sunday/dingyk/tf2/local/lib/python2.7/site-packages/dltrainers/trainers.py", line 16, in <module>
    import dlmodels as dlm
ImportError: No module named dlmodels

**Comment by happog** [comment]
l have found it.

**Comment by akshay94950** [comment]
i also find similar error while trying to run in google colab. @happog can you please tell me how you rectified it?error is shown as below:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-9702febf4cfb> in <module>()
      1 if __name__=="__main__":
----> 2     seg = Segmenter("/content/gdrive/My Drive/Unt/lowskew-000000259-011440.pt")
      3     image = cv2.imread(" /content/gdrive/My Drive/unt/page1.jpg")
      4     lines = seg.extract_textlines(image)
      5     for num,line in enumerate(lines):

2 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    700     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    701     unpickler.persistent_load = persistent_load
--> 702     result = unpickler.load()
    703 
    704     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

ModuleNotFoundError: No module named 'dltrainers'

**Comment by hcolon89** [comment]
Was this solution posted? I'm having the same issue.

**Comment by HaniaGhouse0407** [comment]
hello, i am having the same issue
